services:
  smb-checker:
    build: .
    container_name: smb-acl-tester
    restart: unless-stopped
    # Переменные окружения, чтобы было удобно менять данные авторизации
    environment:
      - SMB_USER=${SMB_USER}
      - SMB_PASS=${SMB_PASS}
      - SMB_SERVER=${SMB_SERVER}
      - SMB_SHARE=${SMB_SHARE}
    # SMB_SERVER - ip or hostname
    # SMB_SHARE - share name
    # Имя пользователя Windows (если учетка локальная, пишите просто имя. Если доменная — DOMAIN\имя)
    # Сетевой режим host может пригодиться, если у вас сложная локальная сеть, 
    # но по умолчанию оставляем стандартный bridge.
    network_mode: bridge
